version: '3.8'

services:
  db:
    build: ./db
    container_name: jbrain-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jbrain_admin
      POSTGRES_PASSWORD: jbrain_password
      POSTGRES_DB: jbrain_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # server:
  #   build: ./server
  #   container_name: jbrain-server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jbrain_db
  #     AI_MODEL_URL: http://host.docker.internal:1234/v1 #Connect to LM Studio

  # client:
  #   build: ./client
  #   container_name: jbrain-client
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server