package com.trandnquang.j_brain.dto.request;

import com.trandnquang.j_brain.dto.response.ExampleResponse;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.util.List;
import java.util.UUID;

/**
 * Request body for creating a new Flashcard.
 *
 * <p>
 * WHY: Phase 3B adds {@code preGeneratedExamples} — when the user opens
 * the word detail drawer, AI examples are generated on-demand and displayed.
 * On Add to Deck, those same examples are passed here so FlashcardService
 * can persist them immediately without triggering a second async generation.
 */
@Data
public class CreateFlashcardRequest {

    @NotNull
    private UUID deckId;

    @NotBlank
    private String cardType; // "WORD" | "KANJI"

    @NotBlank
    private String keyword;

    // ── Phase 2: always sent for words ────────────────────────────────────────
    private String kana;
    private String furigana;
    private Boolean common;

    /**
     * Full structured senses serialized as a JSON string.
     * The backend deserializes and stores in the {@code senses} JSONB column.
     * Schema: [{glosses:string[], pos:string[], misc:string[]}]
     */
    private String serializedSenses;

    // ── Flat meanings: required, extracted from senses[0].glosses by the client ─
    @NotEmpty
    private List<String> meanings;

    // ── Word-specific ──────────────────────────────────────────────────────────
    private List<String> partOfSpeech;
    private String serializedPitchAccent; // JSON string of List<PitchDTO>
    private String audioUrl;

    /** [Phase 2] Kanji chars pre-extracted by backend search, echoed back here */
    private List<String> kanjiComponents;

    // ── Kanji-specific ─────────────────────────────────────────────────────────
    private Integer strokeCount;
    private Integer jlptLevel;
    private List<String> onyomi;
    private List<String> kunyomi;

    /** [Phase 2] Joyo school grade */
    private Integer grade;

    /** [Phase 2] Primary radical */
    private String radical;

    /** [Phase 2] Chinese pinyin readings */
    private List<String> chinese;

    /** [Phase 2] Korean romanized readings */
    private List<String> koreanR;

    /** [Phase 2] Korean Hangul readings */
    private List<String> koreanH;

    /**
     * [Phase 3B] AI examples pre-generated by the word detail drawer.
     * When present, FlashcardService persists these directly instead of
     * triggering a second async generation call.
     * Schema: [{contextStyle, japaneseSentence, furiganaSentence,
     * vietnameseTranslation}]
     */
    private List<ExampleResponse> preGeneratedExamples;
}
